// <auto-generated />
namespace Practical_13_Task2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DatabseAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatabseAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202306090635061_DatabseAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
